### ISSUE TITLE
Ruby 2.0

### ISSUE THREAD

**Issue by daimatz** [daimatz/mamemose#7]
動作確認

**Comment by daimatz** [comment]
大丈夫そう。
いくつかの gem はリビルドが必要かも。

**Comment by daimatz** [comment]
あれー

```
[2013-03-31 04:02:10] ERROR TypeError: wrong argument type nil (expected Hash)
        /Users/dai/repo/mamemose/lib/mamemose.rb:248:in `render'
        /Users/dai/repo/mamemose/lib/mamemose.rb:248:in `markdown'
        /Users/dai/repo/mamemose/lib/mamemose.rb:126:in `req_index'
        /Users/dai/repo/mamemose/lib/mamemose.rb:47:in `block in server'
        /Users/dai/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/webrick/httpservlet/prochandler.rb:38:in `call'
        /Users/dai/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/webrick/httpservlet/prochandler.rb:38:in `do_GET'
        /Users/dai/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/webrick/httpservlet/abstract.rb:106:in `service'
        /Users/dai/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:138:in `service'
        /Users/dai/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/webrick/httpserver.rb:94:in `run'
        /Users/dai/.rbenv/versions/2.0.0-p0/lib/ruby/2.0.0/webrick/server.rb:295:in `block in start_thread'
```
